exclude_paths:
  - vendor
  - bin
  - public
  - lib

detectors:
  IrresponsibleModule:
    enabled: false
  UtilityFunction:
    enabled: false

directories:
  "app/policies":
    FeatureEnvy:
      enabled: false
  "app/controllers":
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  "app/helpers":
    UtilityFunction:
      enabled: false
  "app/mailers":
    InstanceVariableAssumption:
      enabled: false
  "app/models":
    InstanceVariableAssumption:
      enabled: false
