require:
  - rubocop-rails

AllCops:
  EnabledByDefault: true

Metrics/MethodLength:
  Exclude:
    - db/**/*
Metrics/AbcSize:
  Exclude:
    - db/**/*
Metrics/BlockLength:
  Exclude:
    - db/**/*
    - config/**/*

Layout/LineLength:
  Max: 100
  AutoCorrect: true
  IgnoredPatterns: ['(\A|\s)#']

Style/AsciiComments:
  Enabled: false
Style/MissingElse:
  Enabled: false
Style/InlineComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
Style/Copyright:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Exclude: ['Gemfile']

Bundler/GemComment:
  IgnoredGems:
    - rails-i18n
    - haml-rails
    - devise-i18n
    - rubocop
    - rubocop-rails
    - rubocop-rspec
    - web-console
    - spring-watcher-listen