require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  EnabledByDefault: true

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Layout/LineLength:
  Max: 100
  AutoCorrect: true
  IgnoredPatterns: ['(\A|\s)#']

Style/MissingElse:
  Enabled: false
Style/InlineComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
Style/Copyright:
  Enabled: false

Bundler/GemComment:
  IgnoredGems:
    - rails-i18n
    - devise-i18n
    - rubocop
    - rubocop-rails
    - rubocop-rspec
    - web-console
    - spring-watcher-listen

RSpec/ExampleLength:
  Exclude:
    - spec/features/**/*
RSpec/MultipleExpectations:
  Exclude:
    - spec/features/**/*