development:
  clients:
    default:
      database: polos_development
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1
test:
  clients:
    default:
      database: polos_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  sessions:
    default:
      hosts:
        - <%= ENV['DB_HOST'] %>
      database: <%= ENV['DB_NAME'] %>
  options:
    user: <%= ENV['DB_USER'] %>
    password: <%= ENV['DB_PASSWORD'] %>
    roles:
      - 'readWrite'
      - 'dbAdmin'
    include_root_in_json: true
    include_type_for_serialization: true
    scope_overwrite_exception: true